services:
  - type: web
    name: amazon-clone-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_DIALECT
        value: postgres
      - key: JWT_SECRET
        sync: false
