services:
  - type: web
    name: amazon-clone-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        value: dpg-d7g069rbc2fs73ds7gfg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: amazon_clone_db_5b51
      - key: DB_USER
        value: amazon_clone_db_5b51_user
      - key: DB_PASSWORD
        value: cxlz9EwU8bwptM2Kz4nqFneSmpnlI2uW
        sync: false
      - key: JWT_SECRET
        sync: false
